version: "3.8"

services:
    db:
        image: mysql:8

        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: weather_app
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - weather-db:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - 8080:8080
volumes:
    weather-db:
